name: Tests

on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 2
      matrix:
        python-version: ['3.8', '3.9']

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip3 install tox

    - name: Run Tests
      run: |
        mkdir tmp
        tox -e ${{matrix.python-version}}

  validation:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Base Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-venv
        sudo pip3 install poetry

    - name: Install Python Dependencies
      run: |
        poetry install

    - name: Run Validation
      run: |
        poetry run flake8 src
